### PR TITLE
do not install user-identity-mapper

### PR DESCRIPTION
**Pull request by MatousJobanek**
[KUBESAW-169](https://issues.redhat.com/browse/KUBESAW-169)

there is no need to install the user-identity-mapper binary locally (together with the ksctl binary), so the PR is moving the user-identity-mapper directory out of `cmd` folder

### CODE REVIEW

**Review by xcoulon — COMMENTED** [review]
having both `ksctl` and `user-identity-mapper` under `cmd` make it clear that we have 2 CLIs (they both have their own `main.go`). 

I don't see why we need to move the code? I mean, if the concern is about install `ksctl` locally, then it's just a matter of building `cmd/ksctl/main.go`. Or am I missing something?

**Comment by MatousJobanek** [comment]
> having both ksctl and user-identity-mapper under cmd make it clear that we have 2 CLIs 

user-identity-mapper is not really a cli that you would run locally on the daily basis. it's more to be used as a container.

Anyway, how would you change the `make install` command so it installs only `ksctl` binary? When you run `make install` now, then it installs `ksctl` as well as `user-identity-mapper`, and there is no need to install `user-identity-mapper`  locally.

**Comment by xcoulon** [comment]
> > having both ksctl and user-identity-mapper under cmd make it clear that we have 2 CLIs
> 
> user-identity-mapper is not really a cli that you would run locally on the daily basis. it's more to be used as a container.
> 

well, it's a CLI nonetheless, so it makes sense to keep it under the `cmd` folder IMO

> Anyway, how would you change the `make install` command so it installs only `ksctl` binary? When you run `make install` now, then it installs `ksctl` as well as `user-identity-mapper`, and there is no need to install `user-identity-mapper` locally.

Sure, then it's just a matter of updating the [install makefile goal](https://github.com/kubesaw/ksctl/blob/master/make/go.mk#L21) so we only have the `ksctl` binary when running `make install`, and have a separate makefile goal used when building the Docker image?

**Comment by MatousJobanek** [comment]
We don't need to build the `user-identity-mapper` via a makefile target at all - this is done in the Docker image when it's being built: 
https://github.com/kubesaw/ksctl/blob/3b26733db38131551bc1fe08ff9dd6853ca50e62/cmd/user-identity-mapper/Dockerfile#L16-L19

so again, how would you change the `go install` command so it installs `ksctl` only (using the go native functionality, which means also in the location of either `GOBIN` or  `GOPATH`)? I tried that, but I'm doing some mistake there as I cannot achieve the expected outcome, or I'm missing some important flag. Any help is more than welcome :-)

**Comment by mfrancisc** [comment]
> with ${GO_PACKAGE_PATH}/cmd/ksctl/... instead of ${GO_PACKAGE_PATH}/cmd/... seems to work on my machine: I did not have a user-identity-mapper binary after running make install

works for me too! I was about to suggest the same thing.

**Comment by MatousJobanek** [comment]
ok, there was some error between my chair and my keyboard. I was almost 100% sure that I tried that and it didn't built the ksctl binary properly. I maybe omitted the last three dots `/...` :man_shrugging:  :man_facepalming: 
Anyway, thanks for your proposal
Closing this PR...

**Pull request closed without merging**
