### PR TITLE
Switch to Google's uuid module

### PR DESCRIPTION
**Pull request by mikelolasagasti**
`satori/uuid` repo is dead and has different problems as shown in https://github.com/satori/go.uuid/issues/84

Although a fork exists to continue `satori/uuid`, Google's module is simpler and already used as indirect dependency.

### CODE REVIEW

**Review by ranakan19 — COMMENTED** [review]
We compared uuid libraries from google and gofrs at one point and decided to go ahead with gofrs/uuid at that point. Could you try comparing the two libraries, and if not much difference then maybe for the sake of consistency we can use gofrs here as well?

**Review by alexeykazakov — APPROVED** [review]
Thanks!

**Comment by mikelolasagasti** [comment]
> We compared uuid libraries from google and gofrs at one point and decided to go ahead with gofrs/uuid at that point. I'd try comparing the two libraries, and if not much difference then for the sake of consistency it'd be better to use gofrs here as well.

My goal was to reduce the amount of dependencies. gofrs or google's module perform similar, so one or another is not a big change, but Google's is used by 4x more projects than gofrs' module. I can change the PR if required.

What should change is also github.com/codeready-toolchain/toolchain-common to import either a newer gofrs (v3 vs v5) or move to Google's.

**Review by mfrancisc — APPROVED** [review]

**Review by rajivnathan — APPROVED** [review]

**Comment by ranakan19** [comment]
> > We compared uuid libraries from google and gofrs at one point and decided to go ahead with gofrs/uuid at that point. I'd try comparing the two libraries, and if not much difference then for the sake of consistency it'd be better to use gofrs here as well.
> 
> My goal was to reduce the amount of dependencies. gofrs or google's module perform similar, so one or another is not a big change, but Google's is used by 4x more projects than gofrs' module. I can change the PR if required.
> 
> What should change is also github.com/codeready-toolchain/toolchain-common to import either a newer gofrs (v3 vs v5) or move to Google's.

Yep, here is the PR for upgrading the uuid to v5 - https://github.com/codeready-toolchain/toolchain-common/pull/388

**Comment by alexeykazakov** [comment]
Could you please resolve the conflict so we can get it merged?

**Review by fbm3307 — APPROVED** [review]

**Review by ranakan19 — APPROVED** [review]

**Pull request merged**
